// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'byte_stream_source.freezed.dart';

@freezed
sealed class ByteStreamSource with _$ByteStreamSource {
  const ByteStreamSource._();

  const factory ByteStreamSource.path({
    required String path,
  }) = ByteStreamSource_Path;
  const factory ByteStreamSource.bytes({
    required Uint8List bytes,
  }) = ByteStreamSource_Bytes;
  const factory ByteStreamSource.fileDescriptor({
    required int fd,
  }) = ByteStreamSource_FileDescriptor;
  const factory ByteStreamSource.generated({
    required String descriptor,
  }) = ByteStreamSource_Generated;
}
