// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'content_source.freezed.dart';

@freezed
sealed class ContentSource with _$ContentSource {
  const ContentSource._();

  const factory ContentSource.path({
    required String path,
  }) = ContentSource_Path;
  const factory ContentSource.bytes({
    required Uint8List bytes,
  }) = ContentSource_Bytes;
  const factory ContentSource.fileDescriptor({
    required int fd,
  }) = ContentSource_FileDescriptor;
  const factory ContentSource.generated({
    required String descriptor,
  }) = ContentSource_Generated;
}
