// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_isolates/rust/api/content_source.dart';
import 'package:localsend_isolates/rust/api/http.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `take_content`

Future<(RsContentStreamSink, RsContentStreamReceiver)> createContentStream() => RustLib.instance.api.crateApiContentStreamCreateContentStream();

Future<RsContentReader> openContentSource({required RsContentSource source}) =>
    RustLib.instance.api.crateApiContentStreamOpenContentSource(source: source);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsContentReader>>
abstract class RsContentReader implements RustOpaqueInterface {
  Future<void> close();

  Future<Uint8List?> nextChunk();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsContentStreamSink>>
abstract class RsContentStreamSink implements RustOpaqueInterface {
  Future<void> add({required List<int> data});

  Future<void> close();

  /// Returns true when the transfer drops its receiver, or false when this
  /// sink is closed by its producer.
  Future<bool> waitClosed();
}
