// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_isolates/rust/api/cancel.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

/// Measures a replayable application ZIP without storing the archive.
Future<RsMacosAppArchiveInfo> prepareMacosAppArchive({required String path, required RsCancellationToken cancelToken}) =>
    RustLib.instance.api.crateApiMacosAppArchivePrepareMacosAppArchive(path: path, cancelToken: cancelToken);

class RsMacosAppArchiveInfo {
  final String source;
  final BigInt size;
  final String sha256;

  const RsMacosAppArchiveInfo({
    required this.source,
    required this.size,
    required this.sha256,
  });

  @override
  int get hashCode => source.hashCode ^ size.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsMacosAppArchiveInfo && runtimeType == other.runtimeType && source == other.source && size == other.size && sha256 == other.sha256;
}
